"""empty message

Revision ID: a83601e9197f
Revises: fca846b9bd62
Create Date: 2020-10-21 00:27:59.341630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83601e9197f'
down_revision = 'fca846b9bd62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'facebook_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
